[blogvm]
172.17.177.45 ansible_user=vagrant ansible_ssh_private_key_file="/Users/bmota/Desktop/DevOps/Blog-Wordpress/.vagrant/machines/blogvm/virtualbox/private_key"

[databasevm]
172.17.177.46 ansible_user=vagrant ansible_ssh_private_key_file="/Users/bmota/Desktop/DevOps/Blog-Wordpress/.vagrant/machines/databasevm/virtualbox/private_key"