---
- name: "Habilitar aplicação do Nginx"
  shell: ufw allow 'Nginx FULL'
  become: yes
    
- name: "Definindo IP publico"
  shell: ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//'
      
- name: "Verificar se o IP está visivel na web"
  shell: curl -4 icanhazip.com

- name: 'Criando diretorio blog'
  file:
    path: /var/www/blog
    state: directory
  become: yes  
      
- name: "Configurando permissão na pasta blog"
  shell: chown -R $USER:$USER /var/www/blog
  become: yes  

- name: "Copia configuração de blog.nginx"
  template:
    src: '/Users/bmota/Desktop/DevOps/Blog-Wordpress/templates/blog.j2'
    dest: '/etc/nginx/sites-available/blog'
  become: yes

- name: "Ativa o site" 
  file:
    src: "/etc/nginx/sites-available/blog"
    dest: "/etc/nginx/sites-enabled"
    state: hard
  become: yes  

- name: "Desvincula o site default"
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  become: yes 

- name: "Mantém configuração após reload do nginx"
  shell: nginx -t
  become: yes

- name: "Reinicia o NGINX"
  shell: systemctl reload nginx
  become: yes

- name: 'Copia index.html para nginx exibir'
  copy:
    src: '/Users/bmota/Desktop/DevOps/Blog-Wordpress/files/index.html'
    dest: '/var/www/blog/index.html'
  become: yes  

- name: 'Cria página de teste do php'
  copy:
    src: '/Users/bmota/Desktop/DevOps/Blog-Wordpress/files/info.php'
    dest: '/var/www/blog/info.php'
  become: yes  

- name: 'Baixando o Wordpress'
  get_url:
    url: 'http://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompactando Wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: /var/www/
    remote_src: yes
  become: yes

- copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configurando o wp-config com as entradas do mysql'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_username }}" }
    - { regex: 'password_here', value: "{{ wp_user_password }}" }
    - { regex: 'localhost', value: "{{ wp_db_ip }}" } #ip do mysql server
  become: yes