---
- name: 'Atualizando pacotes'
  shell: 'sudo apt-get update'

- name: 'Instalando pacotes'
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - nginx
    - php7.2-fpm
    - php7.2
    - libapache2-mod-php7.2
    - php7.2-gd
    - php-ssh2
    - php7.2-mysql
    - python3 