---
- name: 'Instalando pacotes'
  ansible.builtin.apt:
    pkg:
    - nginx
    - php-fpm
    - php
    - libapache2-mod-php
    - php-gd
    - php-ssh2
    - php-mysql
    - python3
    state: latest
    update_cache: yes
  become: yes