---
- name: 'Instalando pacotes'
  ansible.builtin.apt:
    pkg:
    - mysql-server
    - python3-mysqldb
    state: latest
    update_cache: yes
  become: yes

- name: 'Criando o Banco de dados'
  mysql_db:
    name: "{{ wp_db_name }}"
    #login_user: root
    state: present
  become: yes

- name: 'Criando usuario de MySQL'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  become: yes
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - "{{ wp_host_ip }}" #ip do wordpress server

- name: 'Configurando mysql para aceitar conexão remota'
  template:
    src: '/Users/bmota/Desktop/DevOps/Blog-Wordpress/templates/mysqld.cnf.j2'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf' #alterar o bind-address para 0.0.0.0
  become: yes
  notify:
    - restart mysql